sonar.projectKey=orca-backend
sonar.projectName=ORCA Backend
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/logs/**,**/*.test.*,**/coverage/**
sonar.tests=tests
sonar.test.inclusions=**/*.test.js
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info