name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  security-checks:
    needs: [build]
    uses: ./.github/workflows/security-checks.yml
    secrets: inherit
    permissions:
      security-events: write
      actions: read
      contents: read